version: '3'
services:
  node-app:
    build:
      context: .
      target: development
      args:
        - NODE_ENV=development
    volumes:
      - D:\Repo\next-plate/src:/app/src
    environment:
      - NODE_ENV=development
    command: npm run dev
